import { initializeApp } from 'firebase/app';
import { getAuth } from 'firebase/auth';
import { getFirestore } from 'firebase/firestore';

// Try to import the local config if it exists. 
// This file is generated by AI Studio but ignored by Git to avoid leaking secrets.
let firebaseConfigLocal: any = {};
try {
  // @ts-ignore - this file might be missing in CI/Production if using environment variables
  const config = await import('../../firebase-applet-config.json');
  firebaseConfigLocal = config.default || config;
} catch (e) {
  // File missing, expected in GitHub Actions / CI
}

const firebaseConfig = {
  apiKey: import.meta.env.VITE_FIREBASE_API_KEY || firebaseConfigLocal.apiKey,
  authDomain: import.meta.env.VITE_FIREBASE_AUTH_DOMAIN || firebaseConfigLocal.authDomain,
  projectId: import.meta.env.VITE_FIREBASE_PROJECT_ID || firebaseConfigLocal.projectId,
  storageBucket: import.meta.env.VITE_FIREBASE_STORAGE_BUCKET || firebaseConfigLocal.storageBucket,
  messagingSenderId: import.meta.env.VITE_FIREBASE_MESSAGING_SENDER_ID || firebaseConfigLocal.messagingSenderId,
  appId: import.meta.env.VITE_FIREBASE_APP_ID || firebaseConfigLocal.appId,
};

const databaseId = import.meta.env.VITE_FIREBASE_DATABASE_ID || firebaseConfigLocal.firestoreDatabaseId;

if (!firebaseConfig.apiKey) {
  console.error('Firebase configuration is missing! Please set VITE_FIREBASE_API_KEY and other related environment variables in your deployment settings.');
}

const app = initializeApp(firebaseConfig);
export const db = getFirestore(app, databaseId);
export const auth = getAuth(app);
